name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file dockerfile --tag nginx-pptexam:latest 
      
    - name: Test before scan
      run: |
        docker run -d -p 8080:80 nginx-pptexam
        docker ps -a
        docker inspect nginx-pptexam  
      
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
         image-ref: nginx-pptexam:latest
         severity: 'CRITICAL,HIGH'

   
    
      
    - name: Log in to Docker registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Push Docker image
      run: |
        docker tag nginx-pptexam:latest ankit1400/nginx-pptexam
        docker push ankit1400/nginx-pptexam
        
      
