name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file dockerfile --tag nginx-pptexam:latest 
      
    - name: Test
    - run: |
        docker run -d -p 80:80 nginx-pptexam:latest
        curl http://localhost:80
      
      
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
         image-ref: nginx-pptexam:latest
         severity: 'CRITICAL,HIGH'

   
    
      
    - name: Log in to Docker registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Push Docker image
      run: |
        docker tag nginx-pptexam:latest ankit1400/nginx-pptexam
        docker push ankit1400/nginx-pptexam
        
      
    
    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: .github/workflows
        
    - uses: shallwefootball/s3-upload-action@master
      with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: .github/workflows
          
        
        
      
