name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file dockerfile --tag nginx-pptexam:latest 
      
    - name: Install Trivy
      run: |
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_{{ matrix.os }}-{{ matrix.arch }}.deb
          sudo dpkg -i trivy_{{ matrix.os }}-{{ matrix.arch }}.deb

    - name: Scan for Vulnerabilities
      run: |
          trivy --exit-code 1 --severity HIGH,CRITICAL --no-progress ankit1400/nginx-pptexam
    
      
    - name: Log in to Docker registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Push Docker image
      run: |
        docker tag nginx-pptexam:latest ankit1400/nginx-pptexam
        docker push ankit1400/nginx-pptexam
        
      
